# CSC-321: Data Mining and Machine Learning
## Assignment 1: List comprehension and numpy

### Part 1: List comprehension, list indexing
First, read the tutorial at: https://www.programiz.com/python-programming/list-comprehension

Take the following list, below, and use list comprehension to complete the following. You must use list comprehension, and you mmust start with the original list (startList) each time. 

(a) Create a new list from every other element, starting at index 0

(b) Create a new list that contains True for each element in the original list that is even, False if it is odd

(c) Create a new list that replaces the values in the original list with 1, 2 or 3 under the following conditions. If the value is less than 3, make the new value 1, if it's greater than or equal to 3. but below 6, make it equal to 2, otherwise make it 3

(d) Use slicing to make a shallow copy of the complete list. To test, change one element of your new list, and print both lists. Make sure ONLY your new list changes (because lists are pass-by-reference)

(e) Go through the list of lists contained in the variable data, and extract all elements from each list EXCEPT the last one, and put into a new list of lists. You must use list comprehension.

e.g. the output should be: [[1, 2], [4, 5], [7, 8], [10, 11]]

(f) Go through the list of lists contained in the variable data, and create a single list containing ONLY the last element of each nested list. You must use list comprehension.

e.g. the output should be: [3, 6, 9, 12]

In [1]:
# Use this list for a-d above

startList = [2, 7, 1, 9, 1, 4, 8, 10, 2, 3, 5]

#Part 1A
listA = [startList[i] for i in range(len(startList)) if i%2 == 0]
print(listA)

#Part 1B
listB = [True if num%2 == 0 else False for num in startList]
print(listB)

#Part 1C
listC = [1 if num < 3 else 2 if 3<=num<6 else 3 for num in startList]
print(listC)

#Part 1D
listD = startList[:]
listD[1] = 9
print('listD', listD)
print('startList', startList)

# Use this list for e-f above

data = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

#Part 1E
listE = [aList[:-1] for aList in data]
print(listE)

#Part 1F
listF = [aList[len(aList)-1] for aList in data]
print(listF)


[2, 1, 1, 8, 2, 5]
[True, False, False, False, False, True, True, True, True, False, False]
[1, 3, 1, 3, 1, 2, 3, 3, 1, 2, 2]
listD [2, 9, 1, 9, 1, 4, 8, 10, 2, 3, 5]
startList [2, 7, 1, 9, 1, 4, 8, 10, 2, 3, 5]
[[1, 2], [4, 5], [7, 8], [10, 11]]
[3, 6, 9, 12]


### Part 2: Multiple return values

Read the tutorial at: https://www.tutorialspoint.com/How-do-we-return-multiple-values-in-Python

(a) Write a function called minmax, that takes a list as a single argument, and returns two values as a tuple - the minimum value in the list, and the maximum value in a list. 

(b) Use the random.randint(a,b) function to create a list filled with 100 random integers in the range 0 to 100 (inclusive).

(c) Pass this list to your function from (a), capture the two return values into TWO distinct variables, and print them nicely! (i.e. Print two, distinct, meaningful output messages, not just the tuple returned).

In [16]:
import random

#part 2a
def minmax(aList):
    return min(aList),max(aList)

#part 2b
randList = [random.randint(0, 100) for i in range(100)]

#part 2c
aMin, aMax = minmax(randList)
print('list min is', aMin)
print('list max is', aMax)


list min is 0
list max is 98


### Part 3: Numpy

Read the tutorial at: https://machinelearningmastery.com/index-slice-reshape-numpy-arrays-machine-learning-python/
You may also want to check the following for information on array indexing in more detail: https://www.tutorialspoint.com/numpy/numpy_indexing_and_slicing.htm

Then work on the following:

(a) convert the startList to a one dimensional array. Print this array, and it's shape. Nicely.

(b) convert the startList into a two dimensional array, of 4 rows of 3 columns. Print this array, and it's shape. Nicely.

(c) use array slicing on (b) to produce similar output to 1(e) and 1(f) above. One variable containing 4 rows of 2 columns (all the data EXCEPT the last column from each row), and one variable that is a 4 by 1 array, containing the values from the last column. You will need to reshape this last variable (so a (4,) shape is not acceptable, but a (4,1) is). 

In [35]:
import numpy as np

#part 3A
startList = [12,26,18,1,15,18,12,19,2,7,4,9]
data = np.array(startList)
print('data in array form', data)
print('shape of one dimensional array', data.shape)

#part 3B
data2D = np.array(startList)
data2D = data2D.reshape(4, 3)
print('data in 2D array form', data2D)
print('shape of one dimensional array', data2D.shape)

#part 3C
array1E = data2D[:,:-1]
array1F = data2D[:,-1:]
array1F = array1F.reshape(4,1)
print('startList like 1e', array1E)
print('startList like 1f', array1F)

data in array form [12 26 18  1 15 18 12 19  2  7  4  9]
shape of one dimensional array (12,)
data in 2D array form [[12 26 18]
 [ 1 15 18]
 [12 19  2]
 [ 7  4  9]]
shape of one dimensional array (4, 3)
startList like 1e [[12 26]
 [ 1 15]
 [12 19]
 [ 7  4]]
startList like 1f [[18]
 [18]
 [ 2]
 [ 9]]
